### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by naikdhruv** [filiphric/cypress-plugin-xhr-toggle#5]
**Need to use this with Cypress 9.7.0** 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cypress@1.0.0
npm ERR! Found: cypress@9.7.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^9.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@">=10" from cypress-plugin-xhr-toggle@1.0.0
npm ERR! node_modules/cypress-plugin-xhr-toggle
npm ERR!   cypress-plugin-xhr-toggle@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by filiphric** [comment]
Yeah I only support versions 10 and higher. The UI in previous version is different, which would require me to basically build this plugin twice. The benefit is very limited as pre-10 versions are used less and less.
