### ISSUE TITLE
Small glitches

### ISSUE THREAD

**Issue by EvgenyOrekhov** [filiphric/cypress-plugin-xhr-toggle#7]
1. `(xhr)` records appear for a split second when I expand a test
2. The "Turn on XHR visibility" button sometimes doesn't work when I click on it
3. When I click the "Turn on XHR visibility" button, `(xhr)` records get hidden after a couple of seconds automatically

You can see the above glitches here:

https://user-images.githubusercontent.com/8045060/228967568-3d5b15b1-0ee0-47e2-a2e1-469ac608cc39.mov

**Comment by EvgenyOrekhov** [comment]
Cypress version: 12.9.0

**Comment by MoKhajavi75** [comment]
Same here

**Comment by filiphric** [comment]
happy to announce that these were all fixed with 1.2.1 release
